package fluent.framework.order;


public enum OrderFillStatus{

    UNPLACED,

    LIVE_ZERO_FILL,
    LIVE_PARTIAL_FILL,
    LIVE_FULL_FILL,
    LIVE_OVER_FILL,

    CANCELLED_ZERO_FILL,
    CANCELLED_PARTIAL_FILL,
    CANCELLED_FULL_FILL,
    CANCELLED_OVER_FILL,

    MARKET_REJECTED,
    INTERNALLY_REJECTED;

}
